# Generated by Django 4.2 on 2023-04-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0002_category_products'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('total_price', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.products')),
            ],
            options={
                'db_table': 'addtocart',
            },
        ),
    ]
