# Generated by Django 4.2 on 2023-04-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0002_category_products'),
        ('Customer', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.FloatField()),
                ('totalitems', models.FloatField()),
                ('billdate', models.DateField()),
                ('billtime', models.TimeField()),
                ('paymentstatus', models.CharField(choices=[('p', 'pending'), ('c', 'completed')], default='pending', max_length=1)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.client')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='Billdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemprice', models.FloatField()),
                ('quantity', models.FloatField()),
                ('Bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.bill')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.client')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.products')),
            ],
            options={
                'db_table': 'billdetail',
            },
        ),
    ]
